# vim: ft=tmux

##### -------------------------------------------------------------------------
##### Solarized Theme
##### -------------------------------------------------------------------------

# Backgrounds
bg_main="#002b36"
bg_dark="#073642"

# Solarized palette
base01="#586e75"
base00="#657b83"
base0="#839496"
base1="#93a1a1"

# Foregrounds
fg="#eee8d5"
fg_dark="#15161E"

# Accent
yellow="#b58900"

##### -------------------------------------------------------------------------
##### Base UI
##### -------------------------------------------------------------------------

set -g mode-style "fg=${fg},bg=${bg_dark}"

set -g message-style "fg=${fg},bg=${bg_dark}"
set -g message-command-style "fg=${fg},bg=${bg_dark}"

set -g pane-border-style "fg=${bg_dark}"
set -g pane-active-border-style "fg=${fg}"

##### -------------------------------------------------------------------------
##### Status Bar
##### -------------------------------------------------------------------------

set -g status on
set -g status-interval 1
set -g status-justify left

set -g status-style "fg=${base01},bg=${bg_dark}"
set -g status-bg "${bg_main}"

set -g status-left-length 100
set -g status-right-length 100

set -g status-left-style NONE
set -g status-right-style NONE

##### -------------------------------------------------------------------------
##### Left Status
##### -------------------------------------------------------------------------

set -g status-left "\
#[fg=${bg_dark},bg=${fg}] \
#S \
#[fg=${fg},bg=${base1},nobold,nounderscore,noitalics]\
#[fg=${fg_dark},bg=${base1}] \
#(whoami) \
#[fg=${base1},bg=${bg_main}]"

##### -------------------------------------------------------------------------
##### Right Status
##### -------------------------------------------------------------------------

set -g status-right "\
#[fg=${base01},bg=${bg_main},nobold,nounderscore,noitalics]\
#[fg=${base1},bg=${base01}]\
#[fg=${base00},bg=${base01},nobold,nounderscore,noitalics]\
#[fg=${base1},bg=${base00}]\
#[fg=${base1},bg=${base00},nobold,nounderscore,noitalics]\
#[fg=${fg_dark},bg=${base1}] \
#h "

##### -------------------------------------------------------------------------
##### Windows
##### -------------------------------------------------------------------------

setw -g window-status-separator ""

setw -g window-status-style \
    "NONE,fg=${base0},bg=${bg_main}"

setw -g window-status-activity-style \
    "underscore,fg=${base0},bg=${bg_main}"

# Inactive window

setw -g window-status-format "\
#[fg=${bg_main},bg=${bg_main}]\
#[default] \
#I  #{b:pane_current_path} \
#[fg=${bg_main},bg=${bg_main},nobold,nounderscore,noitalics]"

# Active window

setw -g window-status-current-format "\
#[fg=${bg_main},bg=${fg}]\
#[fg=${yellow},bg=${fg}] \
#I \
#[fg=${fg},bg=${yellow}] \
#{b:pane_current_path} \
#[fg=${yellow},bg=${bg_main},nobold]"
